"""Add new field to ApartmentStage

Revision ID: b5906e4b74a2
Revises: de7516a6ed04
Create Date: 2024-08-20 14:15:57.241202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5906e4b74a2'
down_revision: Union[str, None] = 'de7516a6ed04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartment_stages')
    op.drop_table('apartments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('apartment_stages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stage', sa.VARCHAR(length=6), nullable=False),
    sa.Column('is_ready_for_review', sa.BOOLEAN(), nullable=True),
    sa.Column('is_finished', sa.BOOLEAN(), nullable=True),
    sa.Column('apartment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
